name: Build
on: 
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # Add this line for write permissions
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Changed from GH_TOKEN to GITHUB_TOKEN
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build and Publish
      if: startsWith(github.ref, 'refs/tags/')
      run: npm run publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Add token here as well
      
    - name: Regular Build
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: npm run build:win
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: |
          dist/*.exe
          dist/latest.yml

    # Add this step for automatic release publishing
    - name: Publish Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          dist/latest.yml
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}