name: Build
on: 
  push:
    branches:
      - main
    tags:
      - '*'  # Changed from 'v*' to '*' to match your tag format

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build and Publish
      if: startsWith(github.ref, 'refs/tags/')  # Changed from 'refs/tags/v' to 'refs/tags/'
      run: npm run publish
      
    - name: Regular Build
      if: "!startsWith(github.ref, 'refs/tags/')"  # Changed from 'refs/tags/v' to 'refs/tags/'
      run: npm run build:win
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: |
          dist/*.exe
          dist/latest.yml